// <auto-generated />
using Core.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core.Model.Migrations.SqlLite
{
    [DbContext(typeof(SqlLiteContext))]
    [Migration("20200815180701_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Core.Model.LocationRecords", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastIndex")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastKey")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("LocationRecords");
                });

            modelBuilder.Entity("Core.Model.RepeatingTable", b =>
                {
                    b.Property<string>("DetailID")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemInfo")
                        .HasColumnType("TEXT");

                    b.HasKey("DetailID");

                    b.ToTable("RepeatingTables");
                });
#pragma warning restore 612, 618
        }
    }
}
